exit if ENV['MERCURY_URL'] # don't use master branch
# Load all component sets.
require 'active_support'
require 'active_support/core_ext'
require 'parse/stack'
require 'sucker_punch'
require 'redis'
require 'moneta'
require 'dotenv'
require_relative 'warpcore/config'
require_relative 'warpcore/cache'
require_relative 'warpcore/dispatch'
require_relative 'warpcore/sidekiq'
require_relative 'warpcore/tasks'
require_relative 'warpcore/version'
require_relative 'warpcore/web'
require_relative 'warpcore/parse_stack'
